[mgr]
append_keymap = [
  # directories shortcuts
  { on = ['g', 'b'], run = 'cd ~/.Trash', desc = "Go to Trash" },
  { on = ['g', '.'], run = 'cd ~/.dotfiles', desc = "Go to .dotfiles" },
  { on = ['g', 'p'], run = 'cd ~/Projects', desc = "Go to Projects" },
  { on = ['g', '/'], run = 'cd /', desc = "Go to root" },
  { on = ['g', 'v'], run = 'cd /Volumes', desc = "Go to /Volumes" },

  # navigation
  { on = "<S-Up>", run = "arrow -5", desc = "Move cursor 10 lines up" },
  { on = "<S-Down>", run = "arrow 5", desc = "Move cursor 10 lines down" },

  # linemode shoftcut
  { on = ["m", "c"], run = "linemode custom_mtime", "desc" = "Linemode: custom mtime" },
  { on = ["m", "C"], run = "linemode custom_sizemtime", "desc" = "Linemode: custom sizemtime" },

  # WFT! Shift works with arrow keys, but not PageUp/Down, Enter, etc.
  #
  # # testing
  # { on = "<S-PageUp>", run = "arrow -1", desc = "testing" },
]
